Add schema-based rules for pluggable monitor dependencies data of package index
arduino/arduino-lint pull request #293
Opened 2021-11-11 15:30 UTC by per1234

These are the JSON schema-based rules to check the [`packages[].platforms[].monitorDependencies[]`-level data](https://arduino.github.io/arduino-cli/dev/package_index_json-specification/#platforms-definitions) of Arduino Package Index projects.

2021-11-12 08:53 UTC, silvanocerza commented on internal/project/projectdata/testdata/packageindexes/empty-ids/package_foo_index.json
> +              "name": "networ-monitor"
```suggestion
              "name": "network-monitor"
```

2021-11-12 09:01 UTC, silvanocerza requested changes
Some small typos need to be fixed but the rest looks great. :+1:

2021-11-12 16:23 UTC, per1234 commented on internal/project/projectdata/testdata/packageindexes/empty-ids/package_foo_index.json
> +              "name": "networ-monitor"
Fixed. Thanks!
https://github.com/arduino/arduino-lint/blob/ec2851f01e9eaa88324e35061f49968d9a7791ea/internal/project/projectdata/testdata/packageindexes/empty-ids/package_foo_index.json#L50

2021-11-12 16:25 UTC, per1234 commented on internal/rule/ruleconfiguration/ruleconfiguration.go
> +		ID:               "IL72",
Fixed. Thanks!
https://github.com/arduino/arduino-lint/blob/ec2851f01e9eaa88324e35061f49968d9a7791ea/internal/rule/ruleconfiguration/ruleconfiguration.go#L4793

2021-11-17 13:25 UTC, silvanocerza approved these changes

2021-11-17 15:44 UTC, merged